title: exampleOS
description: exampleOS is an OS for reference purposes
author: Technocoder

url: https://techno-coder.github.io/example_os/
baseurl: /example_os

google_analytics: UA-120286070-1
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
