[package]
name = "kernel"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "*"
multiboot2 = "^0.5.0"
x86_64 = "^0.1.2"
spin = "^0.4.8"
rustc-demangle = "^0.1.8"
bitflags = "^1.0"
bit_field = "^0.7.0"
linked_list_allocator = "^0.6.2"
